---

stages:
  - upload

upload_index_file_to_blob:
  stage: upload
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/azure-cli:1.15.0
  script:
    - az storage blob upload --container-name errorpage --name index.html --file index.html
  only:
    - master
